[package]
name = "solana-wallet-tracker"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-client = "1.17"
solana-sdk = "1.17"
solana-account-decoder = "1.17"
spl-token = { version = "3.5", features = ["no-entrypoint"] }
base64 = "0.21"
dotenv = "0.15"
solana-program = "1.18"
